[package]
name = "day_19"
version = "0.1.0"
edition = "2021"
authors = ["weichslgartner <weichslgartner@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
regex = "1.10.2"

